/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aston.course.module2;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {

  private static List<Student> loadCsvData() {
    Map<String, Student> students = new HashMap<>();

    try (
      InputStream is = App.class.getClassLoader().getResourceAsStream("data.csv");
      BufferedReader reader = new BufferedReader(new InputStreamReader(is));
    ) {
      reader.readLine();

      String line;

      while ((line = reader.readLine()) != null) {
        String[] dataParts = line.split(",");
        String studentName = dataParts[0].trim();
        students.putIfAbsent(studentName, new Student(studentName));

        Book book = new Book(
          dataParts[1].trim(),
          dataParts[2].trim(),
          Integer.parseInt(dataParts[3].trim()),
          new SimpleDateFormat("yyyy-MM-dd").parse(dataParts[4].trim())
        );

        students.get(studentName).addBook(book);
      }

      return students.values().stream().toList();
    } catch (IOException | ParseException e) {
      throw new RuntimeException("Failed to parse data", e);
    }
  }

  private static Boolean bookPublishedAfter2k(Book book) {
    return book.getPublicationYear() > 2000;
  }


  public static void main(String[] args) {
    try {
      List<Student> students = loadCsvData();

      students.stream()
        .peek(System.out::println)
        .flatMap(s -> s.getBooks().stream())
        .sorted(Comparator.comparingInt(Book::pages))
        .distinct()
        .filter(App::bookPublishedAfter2k)
        .limit(3)
        .map(Book::getPublicationYear)
        .findFirst()
        .ifPresentOrElse(
          System.out::println,
          () -> System.out.println("Not found")
        );
    } catch (Exception e) {
      System.out.println("Something went wrong");
      System.out.println(e);
    }
  }
}
